
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FOR_LOOP FUNCTION_DECLARATION FUNCTION_DEF IF_STATEMENT OTHER VARIABLE_DECLARATION\n    construct : VARIABLE_DECLARATION\n              | IF_STATEMENT\n              | FUNCTION_DECLARATION\n              | FUNCTION_DEF\n              | FOR_LOOP\n              | OTHER\n    '
    
_lr_action_items = {'VARIABLE_DECLARATION':([0,],[2,]),'IF_STATEMENT':([0,],[3,]),'FUNCTION_DECLARATION':([0,],[4,]),'FUNCTION_DEF':([0,],[5,]),'FOR_LOOP':([0,],[6,]),'OTHER':([0,],[7,]),'$end':([1,2,3,4,5,6,7,],[0,-1,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'construct':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> construct","S'",1,None,None,None),
  ('construct -> VARIABLE_DECLARATION','construct',1,'p_construct','yacc.py',7),
  ('construct -> IF_STATEMENT','construct',1,'p_construct','yacc.py',8),
  ('construct -> FUNCTION_DECLARATION','construct',1,'p_construct','yacc.py',9),
  ('construct -> FUNCTION_DEF','construct',1,'p_construct','yacc.py',10),
  ('construct -> FOR_LOOP','construct',1,'p_construct','yacc.py',11),
  ('construct -> OTHER','construct',1,'p_construct','yacc.py',12),
]
